apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: krali4-frontend
  namespace: __NAMESPACE__
  labels:
    app: krali4-frontend
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - __INGRESS_HOST__
  rules:
    - host: __INGRESS_HOST__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: krali4-frontend
                port:
                  number: 80
