apiVersion: v1
kind: Service
metadata:
  name: krali4-frontend
  namespace: __NAMESPACE__
  labels:
    app: krali4-frontend
spec:
  type: ClusterIP
  selector:
    app: krali4-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
