export const API = "";
export const SESSION_STORAGE_KEY = "terminal-portfolio-session-id";

export const fallbackSession = {
  session_id: "anon",
  prompt: "krali4@roguehost:~$",
  input_mode: "text",
  connected: false,
  connection_target: "",
  connection_since: "",
  boot_lines: [
    " ,_     _            krali4@unknown",
    " |\\\\_,-~/            --------------",
    " / _  _ |    ,--. OS: unknown x86_64",
    "(  @  @ )   / ,-' Host: unknown",
    " \\  _T_/-._( (    Kernel: 6.1.0-sim",
    " /         `. \\   Shell: bash 5.1",
    "|         _  \\ |  Node: offline",
    " \\ \\ ,  /      |  Seed: --",
    "  || |-_\\__   /",
    " ((_/`(____,-'",
  ],
  suggestions: ["cat README", "ls -la", "tree", "whoami", "ps", "find / -name '*'"],
  commands: [
    "help",
    "pwd",
    "ls [path]",
    "ls -la [path]",
    "cd <path>",
    "tree [path]",
    "cat <file>",
    "grep <pattern> <file>",
    "find [path] -name <pattern>",
    "whoami",
    "id",
    "uname",
    "uname -a",
    "date",
    "ps",
    "netstat",
    "sudo -l",
    "sudo <command>",
    "ssh <user@host>",
    "exit",
    "echo <text>",
    "clear",
    "ll -> ls -la",
  ],
};

export const state = {
  sessionId: fallbackSession.session_id,
  prompt: fallbackSession.prompt,
  inputMode: fallbackSession.input_mode,
  connected: fallbackSession.connected,
  connectionTarget: fallbackSession.connection_target,
  connectionSince: fallbackSession.connection_since,
  suggestions: fallbackSession.suggestions,
  commands: fallbackSession.commands,
  history: [],
  historyIndex: 0,
};

export const elements = {
  output: null,
  form: null,
  input: null,
  promptLabel: null,
  promptPreview: null,
  shortcutRack: null,
  statusText: null,
  shell: null,
  connectionBadge: null,
  connectionMeta: null,
  connectionUptime: null,
};
